server:
  port: 8081
spring:
  application:
    name: planning-service
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:planning
    username: rs
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  output:
      ansi:
        enabled: ALWAYS
